apiVersion: apps/v1
kind: Deployment
metadata:
  name: openproject
  labels:
    app: openproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openproject
  template:
    metadata:
      labels:
        app: openproject
    spec:
      containers:
        - name: openproject
          image: openproject/openproject:{{ .Values.openproject.version | default "dev" }}
          command: ['/scripts/openproject.sh']
          env:
            - name: OPENPROJECT_LOG__LEVEL
              value: error
            - name: OPENPROJECT_HOST__NAME
              value: openproject.local
            - name: OPENPROJECT_HTTPS
              value: 'true'
            - name: OPENPROJECT_DEV_EXTRA_HOSTS
              value: openproject.local
            - name: OPENPROJECT_EDITION
              value: standard
            - name: OPENPROJECT_SEED__ADMIN__USER__PASSWORD__RESET
              value: 'false'
            - name: OPENPROJECT_APIV3__ENABLE__BASIC__AUTH
              value: 'true'
            - name: OPENPROJECT_AUTHENTICATION
              value: '{"global_basic_auth":{"user": "admin", "password": "admin"}}'
          {{ if .Values.openproject.localSrcPath }}
            - name: USE_CUSTOM_SOURCE
              value: 'true'
          {{ end }}
          {{ if .Values.openproject.gitSrcBranchName }}
            - name: GIT_SOURCE_BRANCH
              value: {{ .Values.openproject.gitSrcBranchName }}
          {{ end }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: ca-cert
              mountPath: /certs
            - name: scripts
              mountPath: /scripts
            - name: tmp
              mountPath: /tmp
          {{ if .Values.openproject.localSrcPath }}
            - name: local-opdata
              mountPath: /app
          {{ end }}

      volumes:
        - name: tmp
          emptyDir: {}
        - name: ca-cert
          secret:
            secretName: opnc-ca-secret
        - name: scripts
          configMap:
            name: op-configmap
            defaultMode: 0755
      {{ if .Values.openproject.localSrcPath }}
        - name: local-opdata
          hostPath:
            path: {{ .Values.openproject.localSrcPath }}
            type: Directory
      {{ end }}
