apiVersion: apps/v1
kind: Deployment
metadata:
  name: openproject
  labels:
    app: openproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openproject
  template:
    metadata:
      labels:
        app: openproject
    spec:
      containers:
        - name: openproject
          image: openproject/openproject:{{ .Values.openproject.version | default "dev" }}
          command: ['/scripts/openproject.sh']
          env:
            - name: OPENPROJECT_LOG__LEVEL
              value: error
            - name: OPENPROJECT_HOST__NAME
              value: {{ include "opnc.openprojectHost" . }}
            - name: OPENPROJECT_HTTPS
              value: 'true'
            - name: OPENPROJECT_DEV_EXTRA_HOSTS
              value: {{ include "opnc.openprojectHost" . }}
            - name: OPENPROJECT_EDITION
              value: standard
            - name: OPENPROJECT_APIV3__ENABLE__BASIC__AUTH
              value: 'true'
            - name: OPENPROJECT_SEED__ADMIN__USER__NAME
              value: 'admin'
            - name: OPENPROJECT_SEED__ADMIN__USER__PASSWORD
              value: 'admin'
            - name: OPENPROJECT_SEED__ADMIN__USER__PASSWORD__RESET
              value: 'false'
            - name: OPENPROJECT_AUTHENTICATION
              value: >
                {
                  "global_basic_auth": {
                    "user": "admin",
                    "password": "admin"
                  }
                }
          {{ if .Values.openproject.gitSrcBranchName }}
            - name: GIT_SOURCE_BRANCH
              value: {{ .Values.openproject.gitSrcBranchName }}
          {{ end }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: opdata
              mountPath: /var/openproject/assets
            - name: opdb
              mountPath: /var/openproject/pgdata
            - name: scripts
              mountPath: /scripts
            - name: tmp
              mountPath: /tmp
            {{- include "opnc.caCertVolumeMount" . | indent 12 }}

      volumes:
        - name: opdata
          persistentVolumeClaim:
            claimName: opdata-pvc
        - name: opdb
          persistentVolumeClaim:
            claimName: opdb-pvc
        - name: tmp
          emptyDir: {}
        - name: scripts
          configMap:
            name: op-configmap
            defaultMode: 0755
        {{- include "opnc.caCertVolume" . | indent 8 }}
