apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
        - name: download-binaries
          image: alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              wget -qO /shared/bin/curl https://github.com/moparisthebest/static-curl/releases/latest/download/curl-amd64
              wget -qO /shared/bin/jq https://github.com/jqlang/jq/releases/latest/download/jq-linux64
              chmod +x -R /shared
          volumeMounts:
            - name: shared-bin
              mountPath: /shared/bin
      containers:
        - name: keycloak
          image: keycloak/keycloak:{{ .Values.keycloak.version | default "26.2" }}
          command: ['/scripts/entrypoint.sh']
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_USERNAME
              value: keycloak
            - name: KC_DB_PASSWORD
              value: keycloak
            - name: KC_DB_URL
              value: jdbc:postgresql://keycloak-db:5432/keycloak
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: admin
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: admin
            - name: KC_DB_SCHEMA
              value: public
            - name: KC_HOSTNAME
              value: {{ include "opnc.keycloakHost" . }}
            - name: KC_TRANSACTION_XA_ENABLED
              value: 'false'
            # realm configurations
            - name: KC_REALM_NAME
              value: {{ include "opnc.idp.realmName" . }}
            - name: KC_NEXTCLOUD_CLIENT_ID
              value: {{ include "opnc.idp.nextcloudClientId" . }}
            - name: KC_NEXTCLOUD_CLIENT_SECRET
              value: {{ include "opnc.idp.nextcloudClientSecret" . }}
            - name: KC_NEXTCLOUD_CLIENT_HOST
              value: {{ include "opnc.nextcloudHost" . }}
            - name: KC_OPENPROJECT_CLIENT_ID
              value: {{ include "opnc.idp.openprojectClientId" . }}
            - name: KC_OPENPROJECT_CLIENT_SECRET
              value: {{ include "opnc.idp.openprojectClientSecret" . }}
            - name: KC_OPENPROJECT_CLIENT_HOST
              value: {{ include "opnc.openprojectHost" . }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: shared-bin
              mountPath: /shared/bin
            - name: entrypoint
              mountPath: /scripts
            - name: kcdata
              mountPath: /opt/keycloak/data
      volumes:
        - name: shared-bin
          emptyDir: {}
        - name: entrypoint
          configMap:
            name: entrypoint-configmap
            defaultMode: 0755
        - name: kcdata
          persistentVolumeClaim:
            claimName: kcdata-pvc
