---
environments:
  default:
    values:
      - environments/default/config.yaml
---
repositories:
  - name: openproject
    url: https://charts.openproject.org
  - name: nextcloud
    url: https://nextcloud.github.io/helm
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: openproject
    chart: openproject/openproject
    version: ~10.1.2
    values:
      - values/op-values.gotmpl
  - name: nextcloud
    chart: nextcloud/nextcloud
    version: ~7.0.0
    values:
      - values/nc-values.gotmpl
  - name: keycloak
    chart: bitnami/keycloak
    version: ~24.7.5
    values:
      - values/kc-values.gotmpl
  - name: opnc-integration
    chart: ./charts/opnc-integration
    values:
      - values/integration.gotmpl
