---
environments:
  default:
    values:
      - environments/default/config.yaml
  dev:
    values:
      - environments/default/config.yaml
      - environments/dev/config.yaml
---
repositories:
  # Issue: https://github.com/opf/helm-charts/issues/215
  # NOTE: Remove local openproject and use the following once the issue is resolved:
  # - name: openproject
  #   url: https://charts.openproject.org
  - name: nextcloud
    url: https://nextcloud.github.io/helm
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: cert-manager
    url: https://charts.jetstack.io

namespace: opnc-integration

releases:
  - name: cert-manager
    chart: cert-manager/cert-manager
    version: ~1.18.2
    values:
      - crds:
          enabled: true
  - name: opnc-integration
    chart: ./charts/opnc-integration
    values:
      - values/integration.gotmpl
    needs:
      - cert-manager
  - name: openproject
    chart: ./charts/openproject
    values:
      - values/op-values.gotmpl
    needs:
      - opnc-integration
  # Issue: https://github.com/opf/helm-charts/issues/215
  # NOTE: Remove local openproject and use the following once the issue is resolved:
  # - name: openproject
  #   chart: openproject/openproject
  #   version: ~10.1.2
  #   values:
  #     - values/op-values.gotmpl
  #   needs:
  #     - opnc-integration
  - name: nextcloud
    chart: nextcloud/nextcloud
    version: ~7.0.0
    values:
      - values/nc-values.gotmpl
    needs:
      - opnc-integration
  - name: keycloak
    chart: bitnami/keycloak
    version: ~24.7.5
    values:
      - values/kc-values.gotmpl
    needs:
      - opnc-integration
