# Nextcloud server host name
# Example: nextcloud.local
nextcloudHost: 'nextcloud.local'
# OpenProject server host name
# Example: openproject.local
openprojectHost: 'openproject.local'
# Keycloak server host name
# Example: keycloak.local
keycloakHost: 'keycloak.local'

nextcloud:
  # Nextcloud version git branch
  # E.g. stable31, stable30, master
  version: ''
  # Integration app setup method
  # NOTE: This is only used if the integration is not already set up
  # Options: 'oauth2', 'sso-nextcloud', 'sso-external'
  integrationAppSetupMethod: 'sso-external'
  enableApps:
    # Add the folloing entry for each app you want to enable
    #   - name: 'app_name'   # Name of the app
    #     version: ''        # [Optional] Release version of the app
    #     gitBranch: ''      # [Optional] Git branch to use as the source
    # NOTE: 'version' will be ignored if 'gitBranch' is set
    - name: 'integration_openproject'
      version: ''
      gitBranch: ''
    - name: 'oidc'
      version: ''
      gitBranch: ''
    - name: 'user_oidc'
      version: ''
      gitBranch: ''
    - name: 'groupfolders'
      version: ''
      gitBranch: ''

openproject:
  fullnameOverride: 'openproject'
  image:
    # OpenProject version (docker image tag)
    tag: '16.1'
  openproject:
    https: true
    host: openproject.local
    admin_user:
      password_reset: 'false'
    oidc:
      enabled: true
      displayName: 'Keycloak'
      identifier: 'openproject'
      secret: 'openproject-secret'
      authorizationEndpoint: '/realms/opnc/protocol/openid-connect/auth'
      tokenEndpoint: '/realms/opnc/protocol/openid-connect/token'
      userinfoEndpoint: '/realms/opnc/protocol/openid-connect/userinfo'
      host: 'keycloak.local'
  environment:
    OPENPROJECT_APIV3__ENABLE__BASIC__AUTH: 'true'
    OPENPROJECT_AUTHENTICATION_GLOBAL__BASIC__AUTH_USER: 'admin'
    OPENPROJECT_AUTHENTICATION_GLOBAL__BASIC__AUTH_PASSWORD: 'admin'
    OPENPROJECT_OPENID__CONNECT_KEYCLOAK_ISSUER: https://keycloak.local/realms/opnc
    OPENPROJECT_OPENID__CONNECT_KEYCLOAK_POST__LOGOUT__REDIRECT__URI: https://openproject.local/
    OPENPROJECT_DB_PASSWORD: 'openproject'
    # Git branch to use as the source
    # NOTE: 'version' will be ignored if this is set
    # Example: dev
    OP_GIT_SOURCE_BRANCH: ''
  extraVolumes:
    - name: entrypoint
      configMap:
        name: op-entry-configmap
        defaultMode: 0755
  extraVolumeMounts:
    - name: entrypoint
      mountPath: /scripts
  postgresql:
    fullnameOverride: 'op-postgresql'
    auth:
      password: 'openproject'
      usePasswordFiles: false
    primary:
      podLabels:
        app.kubernetes.io/name: 'op-postgresql'

keycloak:
  fullnameOverride: 'keycloak'
  service:
    ports:
      http: 8080
  image:
    tag: '26.2.5'
  command: ['/scripts/entrypoint.sh']
  usePasswordFiles: false
  auth:
    adminUser: 'admin'
    adminPassword: 'admin'
  extraEnvVars:
    - name: KEYCLOAK_HOSTNAME
      value: keycloak.local
    - name: KC_REALM_NAME
      value: opnc
    - name: KC_NEXTCLOUD_CLIENT_ID
      value: nextcloud
    - name: KC_NEXTCLOUD_CLIENT_SECRET
      value: nextcloud-secret
    - name: KC_NEXTCLOUD_CLIENT_HOST
      value: nextcloud.local
    - name: KC_OPENPROJECT_CLIENT_ID
      value: openproject
    - name: KC_OPENPROJECT_CLIENT_SECRET
      value: openproject-secret
    - name: KC_OPENPROJECT_CLIENT_HOST
      value: openproject.local
  extraVolumes:
    - name: entrypoint
      configMap:
        name: kc-entry-configmap
        defaultMode: 0755
  extraVolumeMounts:
    - name: entrypoint
      mountPath: /scripts
  cache:
    enabled: false
  postgresql:
    fullnameOverride: 'kc-postgresql'
    primary:
      podLabels:
        app.kubernetes.io/name: 'kc-postgresql'

oidc:
  realmName: 'opnc'
  clients:
    nextcloud:
      id: 'nextcloud'
      secret: 'nextcloud-secret'
    openproject:
      id: 'openproject'
      secret: 'openproject-secret'

ingress:
  # Ingress class name
  className: 'nginx'
  # Issuer name for cert-manager
  issuerName: ''
  # CA secret name
  caSecretName: ''
  # TLS secret name
  tlsSecretName: ''
