nextcloud:
  # Nextcloud version git branch
  # E.g. stable31, stable30, master
  version: ''
  # Git branch to use as the source
  # Example: release/2.9
  integrationAppGitBranch: ''

openproject:
  # OpenProject version (docker image tag)
  # E.g. 16, 15.1, dev
  version: ''
  # Git branch to use as the source
  # Example: dev
  gitSrcBranchName: ''
