nextcloud:
  # Nextcloud version git branch
  # E.g. stable31, stable30, master
  version: ''
  # Integration app version
  # NOTE: Provide the full semantic version
  # Example: 2.9.1
  integrationAppVersion: ''
  # Git branch to use as the source for the integration app
  # NOTE: 'integrationAppVersion' will be ignored if this is set
  # Example: release/2.9
  integrationAppGitBranch: ''

openproject:
  # OpenProject version (docker image tag)
  # E.g. 16, 15.1, dev
  version: ''
  # Git branch to use as the source
  # NOTE: 'version' will be ignored if this is set
  # Example: dev
  gitSrcBranchName: ''
