---
apiVersion: v1
kind: ConfigMap
metadata:
  name: op-entry-configmap
data:
  entrypoint.sh: |
{{ .Files.Get "scripts/openproject/entrypoint.sh" | indent 4 }}

{{ if or .Values.openproject.gitSourceBranch .Values.openproject.localSourcePath }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: op-setupsource-configmap
data:
  setup-op-source.sh: |
{{ .Files.Get "scripts/openproject/setup-op-source.sh" | indent 4 }}
{{ end }}