{{ if .Values.openproject.gitSourceBranch }}
apiVersion: batch/v1
kind: Job
metadata:
  name: op-gitsource-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: openproject-gitsource
          image: openproject/openproject:{{ .Values.openproject.dockerTag | default "dev" }}
          command: ['/scripts/setup-op-git.sh']
          env:
            - name: OP_GIT_SOURCE_BRANCH
              value: '{{ .Values.openproject.gitSourceBranch }}'
          volumeMounts:
            - name: gitsource-script
              mountPath: /scripts/setup-op-git.sh
              subPath: setup-op-git.sh
            - name: op-git-source
              mountPath: /home/app/gitapp
      volumes:
        - name: gitsource-script
          configMap:
            name: op-gitsource-configmap
            defaultMode: 0755
        - name: op-git-source
          persistentVolumeClaim:
            claimName: op-gitsource-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: op-gitsource-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
{{ end }}