# Integration setup method
# Options: 'oauth2', 'sso-nextcloud', 'sso-external'
integrationSetupMethod: 'sso-external'

openprojectHost: openproject.local
nextcloudHost: nextcloud.local
keycloakHost: keycloak.local

oidcProvider:
  name: keycloak
  openprojectClientId: openproject

nextcloud:
  enableApps:
    # Add the folloing entry for each app you want to enable
    #   - name: 'app_name'   # Name of the app
    #     version: ''        # [Optional] Release version of the app
    #     gitBranch: ''      # [Optional] Git branch to use as the source
    # NOTE: 'version' will be ignored if 'gitBranch' is set
    - name: 'integration_openproject'
      version: ''
      # gitBranch: '' - NOT WORKING YET (PERMISSIONS ISSUE)
    - name: 'oidc'
      version: ''
      # gitBranch: '' - NOT WORKING YET (PERMISSIONS ISSUE)
    - name: 'user_oidc'
      version: ''
      gitBranch: ''
    - name: 'groupfolders'
      version: ''
      # gitBranch: '' - NOT WORKING YET (PERMISSIONS ISSUE)

extraVolumes: []
extraVolumeMounts: []
extraEnv: []

ingress:
  # Ingress class name
  className: 'nginx'
  # TLS secret name
  tlsSecretName: 'opnc-tls-secret'
  # Use exisiting TLS secret name. If set, the above tlsSecretName will be ignored.
  existingTlsSecretName: ''
