apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-configmap
data:
{{ range $path, $file := .Files.Glob "scripts/nextcloud/**" }}
  {{ $name := trimPrefix "scripts/nextcloud/" $path | replace "/" "_" }}
  {{ $name }}: |
{{ $.Files.Get $path | indent 4 }}
{{ end }}