apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: ghcr.io/juliusknorr/nextcloud-dev-php83:master
          command: ['/shared/nextcloud.sh']
          env:
            - name: SQL
              value: 'pgsql'
            - name: PROTOCOL
              value: 'https'
            - name: VIRTUAL_HOST
              value: {{ include "opnc.nextcloudHost" . }}
            - name: SERVER_BRANCH
              value: {{ .Values.nextcloud.version | default "stable31" }}
            - name: NEXTCLOUD_AUTOINSTALL
              value: 'YES'
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: {{ include "opnc.nextcloudHost" . }}
            - name: NEXTCLOUD_AUTOINSTALL_APPS_WAIT_TIME
              value: '60'
            - name: INTEGRATION_APP_SETUP_METHOD
              value: {{ .Values.nextcloud.integrationAppSetupMethod | default "sso-external" }}
            - name: OPENPROJECT_HOST
              value: {{ include "opnc.openprojectHost" . }}
            - name: KEYCLOAK_HOST
              value: {{ include "opnc.keycloakHost" . }}
          {{ if .Values.nextcloud.integrationAppGitBranch }}
            - name: INTEGRATION_APP_GIT_BRANCH
              value: {{ .Values.nextcloud.integrationAppGitBranch }}
          {{ end }}
          {{ if .Values.nextcloud.integrationAppVersion }}
            - name: INTEGRATION_APP_VERSION
              value: {{ .Values.nextcloud.integrationAppVersion }}
          {{ end }}
            - name: NEXTCLOUD_ENABLE_APPS
              # Space separated list of apps to enable
              # Generated format: app1@2.4.1 app2@git=branch
              value: {{ range $app := .Values.nextcloud.enableApps -}}
                  {{ $app.name }}{{ if $app.gitBranch }}@git={{ $app.gitBranch }} {{ else }}{{ if $app.version }}@{{ $app.version }}{{ end }} {{ end }}
                {{- end }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: ncdata
              mountPath: /var/www/html/data
            - name: ncconfig
              mountPath: /var/www/html/config
            - name: ncapps
              mountPath: /var/www/html/apps
            - name: tmp
              mountPath: /tmp
            - name: scripts
              mountPath: /shared
            {{- include "opnc.caCertVolumeMount" . | indent 12 }}

      volumes:
        - name: ncdata
          persistentVolumeClaim:
            claimName: ncdata-pvc
        - name: ncconfig
          persistentVolumeClaim:
            claimName: ncconfig-pvc
        - name: ncapps
          persistentVolumeClaim:
            claimName: ncapps-pvc
        - name: tmp
          emptyDir: {}
        - name: scripts
          configMap:
            name: scripts-configmap
            defaultMode: 0755
            items:
            {{- range $path, $_ := .Files.Glob "scripts/nextcloud/**" }}
              - key: {{ trimPrefix "scripts/nextcloud/" $path | replace "/" "_" }}
                path: {{ trimPrefix "scripts/nextcloud/" $path }}
            {{- end -}}
        {{- include "opnc.caCertVolume" . | indent 8 }}
