---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-enable-apps
type: Opaque
data:
  enable-apps: {{ range $app := .Values.nextcloud.enableApps -}}
    {{ $app.name }}{{ if $app.gitBranch }}@git={{ $app.gitBranch }} {{ else }}{{ if $app.version }}@{{ $app.version }}{{ end }} {{ end }}
  {{- end }}
