---
apiVersion: v1
kind: Service
metadata:
  name: database-pgsql
  labels:
    app: database-pgsql
spec:
  selector:
    app: database-pgsql
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: websecure
      port: 433
      targetPort: 433
