---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: opnc-rootca-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
spec:
  secretName: {{ include "opnc.caSecretName" . }}
  isCA: true
  commonName: opnc-root-ca
  duration: 8760h
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: opnc-rootca-issuer
    kind: Issuer

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "opnc.ingressIssuerName" . }}
spec:
  ca:
    secretName: {{ include "opnc.caSecretName" . }}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opnc-tsl-cert
spec:
  secretName: {{ include "opnc.tlsSecretName" . }}
  dnsNames:
    - {{ include "opnc.openprojectHost" . }}
    - {{ include "opnc.nextcloudHost" . }}
    - {{ include "opnc.keycloakHost" . }}
  issuerRef:
    name: {{ include "opnc.ingressIssuerName" . }}
    kind: Issuer
