---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: opnc-rootca-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
spec:
  secretName: {{ .Values.ingress.caSecretName | default "opnc-ca-secret" }}
  isCA: true
  commonName: opnc-root-ca
  duration: 8760h
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: opnc-rootca-issuer
    kind: Issuer

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.ingress.issuerName | default "opnc-ca-issuer" }}
spec:
  ca:
    secretName: {{ .Values.ingress.caSecretName | default "opnc-ca-secret" }}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opnc-tsl-cert
spec:
  secretName: {{ .Values.ingress.tlsSecretName | default "opnc-tsl-secret" }}
  dnsNames:
    - {{ .Values.openprojectHost | default "openproject.local" }}
    - {{ .Values.nextcloudHost | default "nextcloud.local" }}
    - {{ .Values.keycloakHost | default "keycloak.local" }}
  issuerRef:
    name: {{ .Values.ingress.issuerName | default "opnc-ca-issuer" }}
    kind: Issuer
