apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opnc-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: {{ include "opnc.issuerName" . }}
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  tls:
    - hosts:
        - {{ include "opnc.openprojectHost" . }}
        - {{ include "opnc.nextcloudHost" . }}
        - {{ include "opnc.keycloakHost" . }}
      secretName: {{ include "opnc.tlsSecretName" . }}
  rules:
    - host: {{ include "opnc.openprojectHost" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openproject
                port:
                  number: 8080
    - host: {{ include "opnc.nextcloudHost" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud
                port:
                  number: 80
    - host: {{ include "opnc.keycloakHost" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
