apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opnc-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: {{ .Values.ingress.issuerName | default "opnc-ca-issuer" }}
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  tls:
    - hosts:
        - {{ .Values.nextcloudHost | default "nextcloud.local" }}
        - {{ .Values.openprojectHost | default "openproject.local" }}
        - {{ .Values.keycloakHost | default "keycloak.local" }}
      secretName: {{ .Values.ingress.tlsSecretName | default "opnc-tsl-secret" }}
  rules:
    - host: {{ .Values.openprojectHost | default "openproject.local" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openproject
                port:
                  number: 8080
    - host: {{ .Values.nextcloudHost | default "nextcloud.local" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud
                port:
                  number: 80
    - host: {{ .Values.keycloakHost | default "keycloak.local" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
