apiVersion: batch/v1
kind: Job
metadata:
  name: setup-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: setup-integration
          image: ddev/ddev-utilities
          command: ['/scripts/setup-integration.sh']
          env:
            - name: NEXTCLOUD_HOST
              value: '{{ include "opnc.nextcloudHost" . }}'
            - name: OPENPROJECT_HOST
              value: '{{ include "opnc.openprojectHost" . }}'
            - name: KEYCLOAK_HOST
              value: '{{ include "opnc.keycloakHost" . }}'
            - name: INTEGRATION_APP_SETUP_METHOD
              value: '{{ .Values.integrationSetupMethod }}'
            - name: OIDC_KEYCLOAK_PROVIDER_NAME
              value: '{{ include "opnc.oidc.providerName" . }}'
            - name: OIDC_KEYCLOAK_OPENPROJECT_CLIENT_ID
              value: '{{ include "opnc.oidc.openprojectClientId" . }}'
            {{- include "opnc.extraEnv" . | indent 12 }}
          volumeMounts:
            - name: setup-script
              mountPath: /scripts/setup-integration.sh
              subPath: setup-integration.sh
            {{- include "opnc.volumes.extraVolumeMounts" . | indent 12 }}

      volumes:
        - name: setup-script
          configMap:
            name: opnc-setup-configmap
            defaultMode: 0755
        {{- include "opnc.volumes.extraVolumes" . | indent 8 }}
