integration:
  ############################################
  # Integration setup                        #
  ############################################
  # Available options:
  #   - oauth2
  #   - sso-nextcloud
  #   - sso-external
  ############################################
  setupMethod: 'oauth2'
  ingressClassName: ''

openproject:
  fullnameOverride: openproject
  host: openproject.test
  #####################################################
  # Pod container image tag                           #
  # Examples: 16.2, dev                               #
  # NOTE: you might also need to change the image tag #
  #   to get the proper ruby version                  #
  #   if you are using 'gitSourceBranch'              #
  #####################################################
  version: '16'
  ############################################
  # Git branch to use as the source          #
  # Example: dev                             #
  ############################################
  gitSourceBranch: ''
  ############################################
  # Mount and use local source code          #
  # Override 'gitSourceBranch'               #
  ############################################
  localSourcePath: ''
  ####################################################
  # Path to map custom OpenProject source inside pod #
  # NOTE: this will server as APP_PATH               #
  ####################################################
  customSourceMountPath: '/home/app/openproject'
  postgresql:
    host: op-postgresql
    password: openproject
  ############################################
  # Enterprise Token                         #
  ############################################
  enterpriseToken: ''
  ############################################
  # Rails environment                        #
  # Examples: production, development, tests #
  ############################################
  railsEnv: 'production'

nextcloud:
  ############################################
  # Pod container image tag                  #
  # Examples: 30, 31                         #
  ############################################
  version: '31'
  ############################################
  # Git branch to use as the source          #
  # Example: master, stable30                #
  ############################################
  gitSourceBranch: ''
  fullnameOverride: nextcloud
  host: nextcloud.test
  enableApps:
    ############################################################################
    # Nextcloud apps to enable                                                 #
    ############################################################################
    # Add the folloing entry for each app you want to enable
    #   - name: 'app_name'   # Name of the app
    #     version: ''        # [Optional] Release version of the app
    #     gitBranch: ''      # [Optional] Git branch to use as the source
    # NOTE: 'version' will be ignored if 'gitBranch' is set
    ############################################################################
    - name: 'integration_openproject'
      version: ''
      gitBranch: ''
    - name: 'oidc'
      version: ''
      gitBranch: ''
    - name: 'user_oidc'
      version: ''
      gitBranch: ''
    - name: 'groupfolders'
      version: ''
      gitBranch: ''
  postgresql:
    host: nc-postgresql
    database: nextcloud
    username: nextcloud
    password: nextcloud

keycloak:
  version: '26.2.5'
  fullnameOverride: keycloak
  host: keycloak.test
  providerName: keycloak
  realm:
    name: opnc
    clients:
      nextcloud:
        id: nextcloud
        secret: nextcloud-secret
      openproject:
        id: openproject
        secret: openproject-secret
  postgresql:
    host: kc-postgresql

ingress:
  tlsSecretName: 'opnc-tls-secret'
  # Use exisiting TLS secret name. If set, the above tlsSecretName will be ignored.
  existingTlsSecretName: ''
  # path to mount the CA certificate file in the container
  caCertFilePath: /certs/ca.crt
